version: '3.2'
services:
  aglio:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./docs:/projects"
    tty: true
    command: aglio -i sample.apib -s -h 0.0.0.0 -p 8000
  drakov:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - "./docs:/projects"
    tty: true
    command: drakov -f "**/*.apib" --public --watch --p 8001