FORMAT: 1A

# ringo-team-development API仕様書

## User CRUD RESTfulAPI
これはサンプルのドキュメントです。

# Group ユーザー管理API

# ユーザー登録処理 [/user] 

## ユーザー登録処理 [POST] 

ユーザー登録を行う。 以下のパラメータをJSON形式で送信する。

- name (string, required) - ユーザー名。255文字以内。
- birthdate (string, required) - 生年月日。yyyy-MM-dd形式。未来日付は不可。

+ Request  (application/json)
    + Parameters
        + name: API 太郎 (string)
        + birthdate: `2022-01-01`(string)

    + Body
        {
            "name": "API 太郎",
            "birthdate":"2022-01-01"
        }

+ Response 201 (application/json)
    + Body
        {
            "message": "Register Succeed!!"
        }

+ Response 400 (application/json)
    + Body
        {
            "message":"validation error",
            "errors":[
                {
                    "field":"name",
                    "messages":[
                        "cannot be empty",
                        "maximum length is 255"
                    ]
                },
                {
                    "field":"birthdate",
                    "messages":[
                        "cannot be null",
                        "format should be yyyy-MM-dd",
                        "cannot set futre date"
                    ]
                }
            ]
        }

# ユーザー検索処理 [/user] 

## ユーザー検索処理 [GET]


