FORMAT: 1A

# ringo-development 仕様書

## User CRUD RESTfulAPI
これはサンプルのドキュメントです。

# Group ユーザー管理API

# ユーザー登録処理 [/user] 

## ユーザー登録処理 [POST] 

+ Request  (application/json)
    + Attribute
        + name: API 太郎 (string,required) - ユーザー名
        + birthdate: `2022-01-01`(string,required) - ユーザーの誕生日

    + Body
        {
            "name": "API 太郎",
            "birthdate":"2022-01-01"
        }

+ Response 201 (application/json)
    + Body
        {
            message: "Register Succeed!!"
        }

+ Response 400 (application/json)
    + Body
        {
            "message":"validation error",
            "errors":[
                {
                    "field":"name",
                    "messages":[
                        "cannot be empty",
                        "maximum length is 255"
                    ]
                },
                {
                    "field":"birthdate",
                    "messages":[
                        "cannot be null",
                        "format should be yyyy-MM-dd",
                        "cannot set futre date"
                    ]
                }
            ]
        }

# ユーザー検索処理 [/user] 

## ユーザー検索処理 [GET]


